In this notebook we are going to see some fundamentals of Python and of the related packages (Numpy, Scikit-learn, etc.) 

In [1]:
# a comment starts with an hashtag symbol:
print("This will be executed")
#print("This will not")

This will be executed


# Numbers

In [2]:
x = 1 # notice that we didn't need to declare the type, it was automatically inferred
print(x)

1


In Python 3 the division always returns a float

In [3]:
x = 3.0
y = 2.  # the 0 can be omitted: 2.0 == 2.
print(x/y)

1.5


In [4]:
x = 4 # int
y = 2 # int
z = x/y
print('value of x:', x, 'type of x:', type(x))
print('value of z:', z, 'type of z:', type(z))

value of x: 4 type of x: <class 'int'>
value of z: 2.0 type of z: <class 'float'>


The " // " command performs integer division (in general notice the different behaviour of division in Python 2 and Python 3)

In [5]:
x = 3
y = 2
z = x // y
print('value of z:', z, '  type of z: ', type(z))

x = 3.0
y = 2.0
z = x // y
print('value of z:', z, 'type of z:', type(z))

value of z: 1   type of z:  <class 'int'>
value of z: 1.0 type of z: <class 'float'>


# Lists

The list is ordered and elements can be added and removed

In [6]:
a = [20, 2, -6]
print(a)
print(a[2])  # notice that indices start from 0 (differently from Matlab)

[20, 2, -6]
-6


In [7]:
b = ['I','will','pass','ML']
print(b[1])

will


In [8]:
b = []
print(b)
b = list()
print(b)
b.append('I')
b.append('will')
b.append('pass')
b.append('ML')
print(b)
b.remove('ML')
print(b)
print(type(b))

[]
[]
['I', 'will', 'pass', 'ML']
['I', 'will', 'pass']
<class 'list'>


range(start,end) creates an array with all the numbers from (start) to (end-1)

In [9]:
c = range(1,5) # same as for(int i=1; i<5; i++) in java/c
print(c)
print(type(c))
print(list(c))

range(1, 5)
<class 'range'>
[1, 2, 3, 4]


":" indexing similar to Matlab (but notice that ending index value is not included and array indexing starts from 0)

In [10]:
d = [0,1,2,3,4,5,6,7,8,9]
print('d =', d)
print('d[0:10] =', d[0:10])
print('d[:] =', d[:])
print('d[1:10] =', d[1:10])
print('d[0:9] =', d[0:9], ' <- last element is (end-1) !')
print('d[3:] =', d[3:])
print('d[:7] =', d[:7])
print('d[:-2] =', d[:-2])  # shorthand for d[:len(d)-2]
print('d[2] =', d[2])      # notice that this is a number
print('d[2:3] =', d[2:3])  # while this is a list of 1 element

d = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
d[0:10] = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
d[:] = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
d[1:10] = [1, 2, 3, 4, 5, 6, 7, 8, 9]
d[0:9] = [0, 1, 2, 3, 4, 5, 6, 7, 8]  <- last element is (end-1) !
d[3:] = [3, 4, 5, 6, 7, 8, 9]
d[:7] = [0, 1, 2, 3, 4, 5, 6]
d[:-2] = [0, 1, 2, 3, 4, 5, 6, 7]
d[2] = 2
d[2:3] = [2]


# If-then-else

If-then-else have a quite standard behavior. Notice how the indentation is used in place of the parenthesis of other programming languages. And/or/not are written as words not symbols.


In [11]:
x = 3
if x > 2:
    print('x > 2')
else:
    print('x <= 2')
print("The value of x is: " + str(x)) # + concatenate strings
print("The value of x is:" , x) # print automatically adds a space between elements

x > 2
The value of x is: 3
The value of x is: 3


In [12]:
c = 'Good Morning !!!'
if c != "hello":
    print("value of c: " + c)
else:
    print("c has value hello")

value of c: Good Morning !!!


In [13]:
x = 9.9
if (x > 0.0) and (x <10.0):
    print("x is between 0 and 10 (excluded)")
else:
    print("x <= 0 or x >= 10")

x is between 0 and 10 (excluded)


In [14]:
grade = 27.2
course = "Computer Vision"
if (grade > 26) and (not (course != "ML")):
    print("Everything is good")
else:
    print("Need to study for ML!!!")

Need to study for ML!!!


# Iterating over elements

In [15]:
x = list(['I','will','pass','ML'])
for elem in x:
    print(elem)

I
will
pass
ML


In [16]:
x = list(['I','will','pass','ML'])
print('Number of elements: ' , len(x))
for i in range(len(x)):
    print(x[i])

Number of elements:  4
I
will
pass
ML


# Importing packages

In [17]:
import scipy as sp
import numpy as np
import sklearn as sl

# There exist also an optimized version for intel processors (faster)
# can be installed via conda install scikit-learn-intelex -c conda-forge
# Then place in your code 
# from sklearnex import patch_sklearn
# patch_sklearn()

                       

# Arrays in numpy

In [18]:
#create vector given values in it
a = np.array([1.0, 2.0, 3.0])
print('a:')
print(a)
print('a.shape =', a.shape, end='\n\n')

#create matrix  given values in it
b = np.array([[1, 2, 3], [4, 5, 6]])
print('b:')
print(b)
print('b.shape =', b.shape, end='\n\n')

#create matrix of 0's of given size
c = np.zeros((3,2))
print('c:')
print(c)
print('c.shape', c.shape, end='\n\n')

#create matrix of size 1x3 (different from array of 3 elements!)
c1 = np.zeros((1,3))
c1[0,:] = [1, 2, 3]
print('c1:')
print(c1)
print('c1.shape =', c1.shape, ' <- notice the difference with the first example (a) !!', end='\n\n')

#create matrix of 1's of given size
d = np.ones((2,3))
print('d:')
print(d, end='\n\n')

#create identity matrix of given size
e = np.eye(4)
print('e:')
print(e, end='\n\n')

#create random matrix (values in [0,1]) of given size
f = np.random.random((2,4))
print('f:')
print(f, end='\n\n')

a:
[1. 2. 3.]
a.shape = (3,)

b:
[[1 2 3]
 [4 5 6]]
b.shape = (2, 3)

c:
[[0. 0.]
 [0. 0.]
 [0. 0.]]
c.shape (3, 2)

c1:
[[1. 2. 3.]]
c1.shape = (1, 3)  <- notice the difference with the first example (a) !!

d:
[[1. 1. 1.]
 [1. 1. 1.]]

e:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

f:
[[0.13397413 0.83765991 0.60305221 0.22510767]
 [0.38919791 0.95420291 0.28624916 0.92942424]]



# Array indexing in numpy

In [19]:
e = np.array([[1,5,7,9],[2,6,8,10]]);
print(e[:,:])

[[ 1  5  7  9]
 [ 2  6  8 10]]


In [20]:
print(e[:,0:4])

[[ 1  5  7  9]
 [ 2  6  8 10]]


In [21]:
print(e[:,1])

[5 6]


In [22]:
print(e[:,1:3])

[[5 7]
 [6 8]]


In [23]:
print(e[:,1:1])

[]


In [24]:
print(e[:,1:-1])

[[5 7]
 [6 8]]


In [25]:
print(e[0,1:])

[5 7 9]


In [26]:
print(e[0,0:3])

[1 5 7]


# Reading from CSV file [1/2]

We can use the **with** environment to vavoid the explicit f = open(filename) ... f.close()


In [27]:
file_name = "data/marks.csv"
line_c = 0
with open(file_name,'r') as infile:  # infile = open(file_name,'r')
    for line in infile:
        if line_c <=4:  # read only the first 4 lines
            line = line.strip() #strip removes whitespaces and newlines characters
            print("Line:\n"+line) # newline removed ^
            v = line.split(',') # split breaks up the string in chunks delimited by the argument
            print("List: "+str(v))
            print("Elements in list:")
            for i in range(len(v)):
                print(v[i].strip(), end=' ') #strip removes whitespaces
            print('\n')
        line_c += 1
# infile.close() executed automatically when we exit the indented block

Line:
1,23,21,20
List: ['1', '23', '21', '20']
Elements in list:
1 23 21 20 

Line:
2,28,30,29
List: ['2', '28', '30', '29']
Elements in list:
2 28 30 29 

Line:
3,25,20,29
List: ['3', '25', '20', '29']
Elements in list:
3 25 20 29 

Line:
4,27,30,29
List: ['4', '27', '30', '29']
Elements in list:
4 27 30 29 

Line:
5,18,22,26
List: ['5', '18', '22', '26']
Elements in list:
5 18 22 26 



# Writing to file

In [28]:
infile_name = "data/marks.csv"
infile = open(file_name,'r')
line_c = 0
outfile_name = "tmp.txt"
outfile = open(outfile_name,'w')
for line in infile:
    if line_c <=4:
        outfile.write("Line:\n"+line+"\n")
        v = line.split(',')
        outfile.write("List: "+str(v)+"\n")
        outfile.write("Elements in list:\n")
        for i in range(len(v)):
            outfile.write(v[i].strip()+"\n")
    line_c += 1
infile.close()
outfile.write(str(10.))
outfile.close()

# Reading from CSV file [2/2]

In [29]:
import csv

filename = "data/marks.csv"

lines = csv.reader(open(filename, newline=''), delimiter=',')
print('type(lines) = ', type(lines))

for line in lines:
    print(line)

type(lines) =  <class '_csv.reader'>
['1', '23', '21', '20']
['2', '28', '30', '29']
['3', '25', '20', '29']
['4', '27', '30', '29']
['5', '18', '22', '26']
['6', '27', '22', '22']
['7', '25', '24', '23']
['8', '22', '23', '26']
['9', '21', '23', '22']
['10', '28', '30', '29']


In [33]:
import csv

filename = "data/marks.csv"
lines = csv.reader(open(filename, newline=''), delimiter=',')

dataset = list(lines)
print(dataset)
for i in range(len(dataset)):
    dataset[i] = [float(x) for x in dataset[i]]
print(dataset)
print('Number of students:', len(dataset), end='\n\n')
# you can convert lists to numpy for automatic print formatting:
print(np.array(dataset))

[['1', '23', '21', '20'], ['2', '28', '30', '29'], ['3', '25', '20', '29'], ['4', '27', '30', '29'], ['5', '18', '22', '26'], ['6', '27', '22', '22'], ['7', '25', '24', '23'], ['8', '22', '23', '26'], ['9', '21', '23', '22'], ['10', '28', '30', '29']]
[[1.0, 23.0, 21.0, 20.0], [2.0, 28.0, 30.0, 29.0], [3.0, 25.0, 20.0, 29.0], [4.0, 27.0, 30.0, 29.0], [5.0, 18.0, 22.0, 26.0], [6.0, 27.0, 22.0, 22.0], [7.0, 25.0, 24.0, 23.0], [8.0, 22.0, 23.0, 26.0], [9.0, 21.0, 23.0, 22.0], [10.0, 28.0, 30.0, 29.0]]
Number of students: 10

[[ 1. 23. 21. 20.]
 [ 2. 28. 30. 29.]
 [ 3. 25. 20. 29.]
 [ 4. 27. 30. 29.]
 [ 5. 18. 22. 26.]
 [ 6. 27. 22. 22.]
 [ 7. 25. 24. 23.]
 [ 8. 22. 23. 26.]
 [ 9. 21. 23. 22.]
 [10. 28. 30. 29.]]


# Functions

In [31]:
def print_value(x):
    print(str(x))

print_value(10)
print_value('hello')

10
hello


In [32]:
def sign(value):
    if value > 0:
        return 1.
    elif value < 0: # this means elseif, allows to construct checks with multiple cases without annidation
        return -1.
    else:
        return 0.

print(sign(10.2))
print(sign(-0.6))
print(sign(0))

1.0
-1.0
0.0
